language: java
jdk:
  - oraclejdk8
script:
  - "mvn test"
  - "mvn cobertura:cobertura"
services:
  - docker
before_install:
  - docker-compose up
after_success:
  - bash <(curl -s https://codecov.io/bash)